openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
  description: This is the API documentation for the user management system.
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
                profile_picture:
                  type: string
                  format: binary
              required:
                - name
                - username
                - password
                - confirmPassword
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid credentials
        '500':
          description: Internal Server Error
